apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocery-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grocery-backend
  template:
    metadata:
      labels:
        app: grocery-backend
    spec:
      containers:
      - name: grocery-backend
        image: akashbora02/grocery-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: mongodb://mongo-svc:27017/grocerydb
        - name: PORT
          value: "5000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"


---

apiVersion: v1
kind: Service
metadata:
  name: grocery-backend-svc
spec:
  type: ClusterIP
  selector:
    app: grocery-backend
  ports:
  - port: 80
    targetPort: 5000