apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeapp-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: homeapp-frontend
  template:
    metadata:
      labels:
        app: homeapp-frontend
    spec:
      containers:
      - name: homeapp-frontend
        image: akashbora02/homeapp-frontend:latest
        ports:
        - containerPort: 80
        env:
          - name: REACT_APP_GROCERY_API_URL
            value: http://grocery-backend-svc:5000
          - name: REACT_APP_TODOS_API_URL
            value: http://todos-backend-svc:5001

...

apiVersion: v1
kind: Service
metadata:
  name: homeapp-frontend-svc
spec:
  type: ClusterIP
  selector:
    app: homeapp-frontend
  ports:
  - port: 80
    targetPort: 80